name: CI5. CI + Git

on:
  push:
    branches: ["ea/ci-yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAVEN_CACHE_DIR: /home/runner/.m2/repository

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ${{ env.MAVEN_CACHE_DIR }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Prepare Maven cache
        run: mkdir -p ${{ env.MAVEN_CACHE_DIR }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up selenoid/vnc_chrome:121.0
        run: docker pull selenoid/vnc_chrome:121.0

      - name: Docker Compose version
        run: docker compose version

      - name: Build and run tests
        run: docker compose up --build --abort-on-container-exit
        env:
         MAVEN_CACHE_DIR: ${{ env.MAVEN_CACHE_DIR }}

      - name: Save Maven cache from container
        run: docker cp tests2:/root/.m2 ${{ env.MAVEN_CACHE_DIR }}

      - name: Build and run tests
        run: docker compose up --build --abort-on-container-exit

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Ð¡ontainer removal
        if: always()
        run: docker compose down || true
